### ISSUE TITLE
Help with tutorial when attaching nodes in the GMT 

### ISSUE THREAD

**Issue by stefanodallapalma** [radon-h2020/RADON-workshop#8] opened 2021-05-17 08:41 UTC
Hi,

I have followed the tutorial til the GMT section. However, in the ["Attaching the code"](https://github.com/radon-h2020/RADON-workshop/blob/main/labs/gmt.md#attaching-the-code) it is not clear how to fill the form.
For example, for the _update_ item, I have:

* Selected type: zip
* Artifact URL: http://cloudstash.io/artifact_download/0b2516f89dbd44dc1bd03712e81db7
* Assumed the name can be whatever, then I have chosen _Update_

See figure below:

![Screenshot from 2021-05-17 10-31-23](https://user-images.githubusercontent.com/18099827/118458872-728fb800-b6fb-11eb-9f1e-b208c0c7463a.png)

When pressing the "Add" button the following error is displayed:

![Screenshot from 2021-05-17 10-31-33](https://user-images.githubusercontent.com/18099827/118458893-77ed0280-b6fb-11eb-9fae-cba7985c936c.png)

Can you provide that section with further details?
Thank you!

**Comment by AlexSpart** [comment] 2021-05-18 10:56
Hi @stefanodallapalma,
I tried to reproduce the issue but it seems to work just fine.
The configuration you made seems to be correct as well.
Maybe @miwurster  can give any hints based on the error that popped out?

**Comment by miwurster** [comment] 2021-05-18 12:05
I tried it by myself in Winery, but couldn't reproduce the error. Did you spot any error log in your browser's console?
Could you please also check the network tab if the backend reported an HTTP error or if it's "just" a UI issue?

I think as a workaround it should be possible to "Save" and reload the browser tab. Then the dialog should work again.

**Comment by AlexSpart** [comment] 2021-06-13 08:06
Hi @stefanodallapalma, is the issue still persisting?
If not I will close the issue.

**Closed** 2021-06-14 12:55 UTC
